# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160814_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smenu_item_name', models.CharField(max_length=20)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='menu_item',
            name='smenu_items',
        ),
        migrations.DeleteModel(
            name='Menu_Item',
        ),
        migrations.DeleteModel(
            name='Submenu_Item',
        ),
    ]
