# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160815_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(max_length=15, verbose_name=b'Men\xc3\xbc Ad\xc4\xb1'),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='smenu_item_name',
            field=models.CharField(max_length=20, verbose_name=b'Alt Men\xc3\xbc Ad\xc4\xb1'),
        ),
    ]
