# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160815_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Men\xfc Eleman\u0131', 'verbose_name_plural': 'Men\xfc Elemanlar\u0131'},
        ),
        migrations.AlterModelOptions(
            name='submenuitem',
            options={'verbose_name': 'Alt Men\xfc Eleman\u0131', 'verbose_name_plural': 'Alt Men\xfc Elemanlar\u0131'},
        ),
    ]
