# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160815_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuitem',
            name='smenu_item_content',
            field=models.CharField(default='cdfvgfv', max_length=20, verbose_name=b'\xc4\xb0\xc3\xa7erik'),
            preserve_default=False,
        ),
    ]
